version: '3.7'
name: 'db-nestjs-graphql'
services:
  db:
    # postgres:
    container_name: database
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'db-test'
    ports:
      - '5432:5432'
